from django.contrib import admin
from .models import *

admin.site.register(Basket)
admin.site.register(Budget)
admin.site.register(Company)
admin.site.register(Customer)
admin.site.register(Device)
admin.site.register(DeviceCategory)
admin.site.register(DeviceCriteria)
admin.site.register(CategoryCriteria)
admin.site.register(DeviceOfShipment)
admin.site.register(Employee)
admin.site.register(FavoriteDevice)
admin.site.register(Feedback)
admin.site.register(Image)
admin.site.register(Office)
admin.site.register(ProcessorCPU)
admin.site.register(Provider)
admin.site.register(PurchasedDevice)
admin.site.register(PurchaseOrder)
admin.site.register(Shipment)
admin.site.register(Transport)
admin.site.register(WarehouseOfDevice)
